### ISSUE TITLE
컨트롤러 유닛 테스트 시 권한 관련 발생한 문제

### ISSUE THREAD

**Issue by tkddn204** [FastCampusKDTBackend-Toy4/KDT_Y_BE_Toy_Project2#129]
# 문제 설명
## 문제 1

- 여행 등록 테스트를 개발하던 도중, 응답 HTTP 코드가 401 또는 403으로 반환되는 문제가 발생했습니다.
- [외부 블로그 링크](https://sedangdang.tistory.com/303)에 있는 문제와 똑같은 문제여서, 이 부분을 `with(csrf())`를 붙여 해결했습니다.
- (위 블로그 링크에서 마지막 부분을 참고해주세요.)

## 문제 2

그래도 해결이 되지 않고 아래와 같은 에러가 발생했습니다.

```java
java.lang.ClassCastException: class org.springframework.security.core.userdetails.User cannot be cast to class java.lang.String (org.springframework.security.core.userdetails.User is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at com.kdt_y_be_toy_project2.global.resolver.LoginInfoArgumentResolver.resolveArgument(LoginInfoArgumentResolver.java:20) ~[main/:na]
```

- principal을 받아올 때 문자열이 아닌 `User` 객체로 받아오는 것이 원인이었습니다.
- 따라서 테스트 코드에서 `@BeforeEach`에 다음과 같이 테스트용 토큰을 임의로 작성해주었습니다.

```java
@BeforeEach
public void beforeEach() {
	Authentication authentication = new TestingAuthenticationToken("test@test.com", null);
	authentication.setAuthenticated(true);
	SecurityContext securityContext = SecurityContextHolder.getContext();
	securityContext.setAuthentication(authentication);
}
```

## 문제 3

- Jwt 토큰을 생성하기 위해 `JwtProvider` 를 오토와이어링 해서 불러오려 했습니다.
- 하지만 유닛 테스트를 하는 중이었기에 빈을 불러와도 `@Value`를 인식하지 못하는 문제가 발생했습니다.
- 그래서 아래와 `JwtProvier`로 Jwt 토큰을 생성하는 것이 아니라 임의로 Jwt 토큰을 생성해서 헤더에 넣어주었습니다.

```java
private final static String FAKE_JWT_ACCESS_TOKEN = "가짜토큰...";
```

**Comment by Parkgeonmoo** [comment]
좋은 정보 감사합니다!

**Comment by tjdtn0219** [comment]
굿굿!
