### ISSUE TITLE
[fix] DateTimeFormat 관련 에러 수정

### ISSUE THREAD

**Issue by tkddn204** [FastCampusKDTBackend-Toy4/KDT_Y_BE_Toy_Project2#30]
## 의도

* 로컬에서 여행 등록 기능을 테스트하던 도중 다음과 같은 에러가 발생했습니다.

```
JSON parse error: Cannot deserialize value of type `java.time.LocalDateTime` from String "2023-10-25 15:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2023-10-25 15:00' could not be parsed at index 10
```

* 해당 에러를 해결하기 위해 chatGPT에게 물어보니 다음과 같은 답변을 받을 수 있었습니다.

> `@DateTimeFormat`과 `@JsonFormat`은 두 어노테이션이 서로 다른 라이브러리에서 제공되며, 각기 다른 상황에서 사용됩니다.
> 
> `@DateTimeFormat`은 Spring Framework에서 제공하는 어노테이션으로, 주로 Spring MVC에서 들어오는 요청 파라미터나 Thymeleaf와 같은 템플릿 엔진에서 사용됩니다. 예를 들어, 웹 폼 데이터를 서버의 자바 객체로 변환하거나, 서버의 자바 객체를 웹 뷰로 변환할 때 사용됩니다.
> 
> 반면에 `@JsonFormat`은 Jackson 라이브러리에서 제공하는 어노테이션으로, 주로 JSON으로 직렬화하거나 JSON에서 역직렬화할 때 사용됩니다. 따라서 RESTful API에서 클라이언트와 서버 간에 데이터를 주고받을 때 많이 사용합니다.
> 
> 즉, `@DateTimeFormat`은 주로 웹 요청의 파라미터나 템플릿 뷰를 다룰 때 사용되며, `@JsonFormat`은 JSON 데이터를 처리할 때 사용됩니다. 이 둘의 주요한 차이점은 그들이 적용되는 데이터의 유형과 사용되는 상황에 있습니다.

* 위 chatGPT의 답변에 따라 `@DateTimeFormat`으로 작성된 코드들을  모두 `@JsonFormat`으로 변경하려 합니다.
* 또, 변경 전의 날짜 형식이 `YYYY-MM-DD HH:mm` 였는데, 정확한 날짜를 입력받기 위해 `yyyy-MM-dd HH:mm`으로 변경하려 합니다.

## 작업사항

- [x] 여행 관련 요청 DTO(`CreateTripRequest`, `EditTripRequest`)의 `@DateTimeFormat`을 `@JsonFormat`으로 변경한다.
- [x] 잘못된 날짜 포맷을 수정한다.

**Comment by wocjf0513** [comment]
같은 문제를 겪었는데, 확실히 JsonFormat으로 바꾸는 게 사용자 입력 시 편할 거 같습니다.
