### ISSUE TITLE
회원 도에

### ISSUE THREAD

**Issue by Nine-JH** [FastCampusKDTBackend-Toy4/KDT_Y_BE_Toy_Project2#80]
# 의도

* 요구사항에 회원에 대한 기능이 들어가기 때문에 우선적으로 회원 도메인을 생성할 필요가 생겼습니다.
* 현재 최고 우선사항이 엔티티간 연관관계 형성이기 때문에 비즈니스 로직은 후에 제공될 예정입니다.

# 작업내용
* Member Entity 생성
* Member Repository 생성

**Comment by tkddn204** [comment]
감사합니다 👍
